//
//  MealPlanGeneration.swift
//  Buildplate
//
//  Created by AI Assistant on 2025-01-03.
//
//  Models for AI meal plan generation requests and responses.
//

import Foundation

// MARK: - Request Models

/// Request model for AI meal plan generation
struct MealPlanGenerationRequest {
    let age: Int
    let gender: String
    let dietaryPreferences: String
    let budget: String
    let goal: String
    let weekStart: String // ISO date string
    
    /// Creates a request from user profile data
    static func fromUserProfile(_ profile: UserProfile, weekStart: Date) -> MealPlanGenerationRequest {
        let dateFormatter = ISO8601DateFormatter()
        dateFormatter.formatOptions = [.withFullDate]
        
        return MealPlanGenerationRequest(
            age: profile.age ?? 25,
            gender: profile.gender ?? "Not specified",
            dietaryPreferences: profile.diet ?? "No restrictions",
            budget: profile.budget ?? "Medium",
            goal: profile.goal ?? "Healthy eating",
            weekStart: dateFormatter.string(from: weekStart)
        )
    }
}

// MARK: - Response Models

/// Response model from AI meal plan generation
struct MealPlanGenerationResponse: Codable {
    let weekTitle: String
    let totalEstimatedCost: Double
    let meals: [DayMealPlan]
}

/// Represents a day's meal plan from AI generation
struct DayMealPlan: Codable {
    let day: String // "Monday", "Tuesday", etc.
    let dayOfWeek: Int // 0-6
    let breakfast: GeneratedMeal
    let lunch: GeneratedMeal
    let dinner: GeneratedMeal
    
    /// Converts to an array of UI-compatible meals
    func toMeals() -> [Meal] {
        return [
            breakfast.toMeal(category: .breakfast),
            lunch.toMeal(category: .lunch),
            dinner.toMeal(category: .dinner)
        ]
    }
}

/// A single meal generated by AI
struct GeneratedMeal: Codable {
    let name: String
    let cookingTime: Int
    let difficulty: String // "easy", "medium", "hard"
    let ingredients: [String]
    let instructions: [String]
    let estimatedCost: Double
    
    /// Converts to a UI-compatible Meal object
    func toMeal(category: Meal.MealCategory) -> Meal {
        let difficultyLevel: Meal.DifficultyLevel
        switch difficulty.lowercased() {
        case "easy":
            difficultyLevel = .easy
        case "hard":
            difficultyLevel = .hard
        default:
            difficultyLevel = .medium
        }
        
        // Try to find a matching recipe in the existing database
        let recipe = findMatchingRecipe()
        
        return Meal(
            name: name,
            category: category,
            cookingTime: cookingTime,
            difficulty: difficultyLevel,
            imageURL: nil,
            isCompleted: false,
            recipe: recipe
        )
    }
    
    /// Attempts to find a matching recipe from existing recipes
    private func findMatchingRecipe() -> Recipe? {
        let existingRecipes = Recipe.enhancedMockRecipes()
        
        // First, try exact name match
        if let exactMatch = existingRecipes.first(where: { $0.title.lowercased() == name.lowercased() }) {
            return exactMatch
        }
        
        // Then try partial matches based on keywords
        let nameWords = name.lowercased().components(separatedBy: .whitespaces)
        let partialMatch = existingRecipes.first { recipe in
            let recipeWords = recipe.title.lowercased().components(separatedBy: .whitespaces)
            return nameWords.contains { nameWord in
                recipeWords.contains { recipeWord in
                    recipeWord.contains(nameWord) || nameWord.contains(recipeWord)
                }
            }
        }
        
        if let match = partialMatch {
            return match
        }
        
        // If no match found, create a new recipe from AI data
        return createRecipeFromGeneratedMeal()
    }
    
    /// Creates a new Recipe object from the AI-generated meal data
    private func createRecipeFromGeneratedMeal() -> Recipe {
        let recipeIngredients = ingredients.enumerated().map { index, ingredient in
            // Parse ingredient string to create proper Ingredient objects
            let parts = ingredient.components(separatedBy: " ")
            let quantity = parts.first(where: { $0.contains(where: \.isNumber) }) ?? "1"
            let name = parts.filter { !$0.contains(where: \.isNumber) }.joined(separator: " ")
            
            return Ingredient(
                name: name.isEmpty ? ingredient : name,
                quantity: quantity,
                category: categorizeIngredient(ingredient),
                emoji: getIngredientEmoji(ingredient)
            )
        }
        
        return Recipe(
            id: UUID().uuidString,
            title: name,
            cookTime: "\(cookingTime) mins",
            prepTime: 10,
            servings: 4,
            calories: 400,
            imageUrl: nil,
            ingredients: ingredients, // Use string ingredients
            steps: instructions,
            substitutions: [],
            tags: [difficulty.capitalized, "AI Generated"],
            difficulty: difficulty,
            cuisineType: "Western",
            costEstimate: estimatedCost,
            createdAt: Date(),
            updatedAt: Date(),
            createdBy: "AI",
            isPublic: true,
            rating: 4.0,
            ratingCount: 1
        )
    }
    
    /// Categorizes an ingredient based on common patterns
    private func categorizeIngredient(_ ingredient: String) -> String {
        let lowerIngredient = ingredient.lowercased()
        
        if lowerIngredient.contains("meat") || lowerIngredient.contains("beef") || 
           lowerIngredient.contains("chicken") || lowerIngredient.contains("fish") || 
           lowerIngredient.contains("salmon") || lowerIngredient.contains("pork") {
            return "Meat"
        } else if lowerIngredient.contains("rice") || lowerIngredient.contains("flour") || 
                  lowerIngredient.contains("pasta") || lowerIngredient.contains("bread") || 
                  lowerIngredient.contains("oats") || lowerIngredient.contains("quinoa") {
            return "Grains"
        } else if lowerIngredient.contains("tomato") || lowerIngredient.contains("onion") || 
                  lowerIngredient.contains("lettuce") || lowerIngredient.contains("carrot") || 
                  lowerIngredient.contains("bell pepper") || lowerIngredient.contains("mushroom") {
            return "Vegetables"
        } else if lowerIngredient.contains("oil") || lowerIngredient.contains("butter") {
            return "Oils"
        } else if lowerIngredient.contains("salt") || lowerIngredient.contains("pepper") || 
                  lowerIngredient.contains("spice") || lowerIngredient.contains("garlic") || 
                  lowerIngredient.contains("herb") {
            return "Spices"
        } else if lowerIngredient.contains("milk") || lowerIngredient.contains("water") || 
                  lowerIngredient.contains("stock") || lowerIngredient.contains("broth") {
            return "Liquids"
        } else if lowerIngredient.contains("bean") || lowerIngredient.contains("lentil") || 
                  lowerIngredient.contains("chickpea") {
            return "Legumes"
        } else if lowerIngredient.contains("cheese") || lowerIngredient.contains("yogurt") || 
                  lowerIngredient.contains("cream") {
            return "Dairy"
        } else {
            return "Other"
        }
    }
    
    /// Returns an appropriate emoji for an ingredient
    private func getIngredientEmoji(_ ingredient: String) -> String {
        let lowerIngredient = ingredient.lowercased()
        
        if lowerIngredient.contains("meat") || lowerIngredient.contains("beef") {
            return "🥩"
        } else if lowerIngredient.contains("chicken") {
            return "🐔"
        } else if lowerIngredient.contains("fish") || lowerIngredient.contains("salmon") {
            return "🐟"
        } else if lowerIngredient.contains("rice") {
            return "🍚"
        } else if lowerIngredient.contains("flour") || lowerIngredient.contains("bread") {
            return "🍞"
        } else if lowerIngredient.contains("pasta") {
            return "🍝"
        } else if lowerIngredient.contains("oats") || lowerIngredient.contains("quinoa") {
            return "🌾"
        } else if lowerIngredient.contains("tomato") {
            return "🍅"
        } else if lowerIngredient.contains("onion") {
            return "🧅"
        } else if lowerIngredient.contains("lettuce") || lowerIngredient.contains("green") {
            return "🥬"
        } else if lowerIngredient.contains("carrot") {
            return "🥕"
        } else if lowerIngredient.contains("mushroom") {
            return "🍄"
        } else if lowerIngredient.contains("bell pepper") {
            return "🫑"
        } else if lowerIngredient.contains("oil") {
            return "🫒"
        } else if lowerIngredient.contains("salt") {
            return "🧂"
        } else if lowerIngredient.contains("garlic") {
            return "🧄"
        } else if lowerIngredient.contains("milk") {
            return "🥛"
        } else if lowerIngredient.contains("water") {
            return "💧"
        } else if lowerIngredient.contains("bean") || lowerIngredient.contains("chickpea") {
            return "🫘"
        } else if lowerIngredient.contains("cheese") {
            return "🧀"
        } else if lowerIngredient.contains("avocado") {
            return "🥑"
        } else {
            return "🥄"
        }
    }
}

// MARK: - UI State Models

/// UI state for the meal plan generation process
enum MealPlanGenerationState {
    case idle
    case generating
    case generated(MealPlanGenerationResponse)
    case saving
    case saved(Plan)
    case error(String)
}

/// User preferences for meal plan generation
struct MealPlanPreferences {
    let weekStartDate: Date
    let budget: String
    let dietaryRestrictions: [String]
    let goals: [String]
    let excludedIngredients: [String]
    
    static let budgetOptions = ["Low ($40-60)", "Medium ($60-100)", "High ($100+)"]
    static let commonDietaryRestrictions = ["Vegetarian", "Vegan", "No Pork", "No Beef", "Gluten-Free", "Dairy-Free"]
    static let commonGoals = ["Weight Loss", "Weight Gain", "Muscle Building", "General Health", "Energy Boost"]
} 