//
//  MealPlan.swift
//  Makuli
//
//  Created by Ian   on 19/06/2025.
//

import Foundation

/**
 * MealPlan Model
 * 
 * Represents a meal plan entity that contains multiple meals organized by day and meal type.
 * This model is used for displaying meal plans in the UI and managing meal plan data.
 * 
 * Key Features:
 * - Links to a user's plan via plan_id
 * - Contains meals organized by day and meal type (breakfast, lunch, dinner, snacks)
 * - Supports meal plan generation and management
 * 
 * Database Relationships:
 * - Belongs to a Plan (via plan_id)
 * - Contains multiple meals organized by day and meal type
 */
struct MealPlan: Identifiable, Codable {
    /// Unique identifier for the meal plan
    let id: String
    
    /// Reference to the parent plan
    let planId: String
    
    /// Collection of meals organized by day and meal type
    let meals: [String: [String: [Meal]]]
    
    /// Timestamp when the meal plan was created
    let createdAt: Date
    
    /// Timestamp when the meal plan was last updated
    let updatedAt: Date
    
    /// Flag to indicate if this plan was generated by Spoonacular
    var isSpoonacularGenerated: Bool = false
    
    // MARK: - Coding Keys
    
    enum CodingKeys: String, CodingKey {
        case id
        case planId = "plan_id"
        case meals
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case isSpoonacularGenerated
    }
    
    // MARK: - Custom Decoder
    
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        
        id = try container.decode(String.self, forKey: .id)
        planId = try container.decode(String.self, forKey: .planId)
        
        // Decode meals with proper date handling
        let mealsData = try container.decode([String: [String: [Meal]]].self, forKey: .meals)
        meals = mealsData
        
        // Handle date decoding with ISO8601 format
        let dateFormatter = ISO8601DateFormatter()
        dateFormatter.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        
        if let createdAtString = try? container.decode(String.self, forKey: .createdAt) {
            createdAt = dateFormatter.date(from: createdAtString) ?? Date()
        } else {
            createdAt = Date()
        }
        
        if let updatedAtString = try? container.decode(String.self, forKey: .updatedAt) {
            updatedAt = dateFormatter.date(from: updatedAtString) ?? Date()
        } else {
            updatedAt = Date()
        }
        // Decode isSpoonacularGenerated if present, otherwise default to false
        isSpoonacularGenerated = (try? container.decode(Bool.self, forKey: .isSpoonacularGenerated)) ?? false
    }
    
    // MARK: - Convenience Initializer
    
    /**
     * Creates a new MealPlan instance
     * 
     * - Parameters:
     *   - id: Unique identifier
     *   - planId: Reference to the parent plan
     *   - meals: Dictionary of meals organized by day and meal type
     *   - createdAt: Creation timestamp
     *   - updatedAt: Last update timestamp
     *   - isSpoonacularGenerated: Whether this plan was generated by Spoonacular (default: false)
     */
    init(id: String, planId: String, meals: [String: [String: [Meal]]], createdAt: Date, updatedAt: Date, isSpoonacularGenerated: Bool = false) {
        self.id = id
        self.planId = planId
        self.meals = meals
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.isSpoonacularGenerated = isSpoonacularGenerated
    }
    
    // MARK: - Helper Methods
    
    /**
     * Gets meals for a specific day
     * 
     * - Parameter day: The day to get meals for (e.g., "Monday", "Tuesday")
     * - Returns: Dictionary of meals organized by meal type, or empty dictionary if no meals found
     */
    func mealsForDay(_ day: String) -> [String: [Meal]] {
        return meals[day] ?? [:]
    }
    
    /**
     * Gets meals for a specific day and meal type
     * 
     * - Parameters:
     *   - day: The day to get meals for
     *   - mealType: The meal type (breakfast, lunch, dinner, snacks)
     * - Returns: Array of meals, or empty array if no meals found
     */
    func mealsForDay(_ day: String, mealType: String) -> [Meal] {
        return meals[day]?[mealType] ?? []
    }
    
    /**
     * Gets all unique days that have meals
     * 
     * - Returns: Array of day names
     */
    var allDays: [String] {
        return Array(meals.keys).sorted()
    }
    
    /**
     * Gets all meal types available in the meal plan
     * 
     * - Returns: Array of meal type names
     */
    var allMealTypes: [String] {
        let allTypes = Set(meals.values.flatMap { $0.keys })
        return Array(allTypes).sorted()
    }
    
    /**
     * Gets the total number of meals in the plan
     * 
     * - Returns: Total count of all meals across all days and types
     */
    var totalMealCount: Int {
        return meals.values.flatMap { $0.values }.flatMap { $0 }.count
    }
}
